services:
  crud_test_app:
    build: .
    image: crud-test-app
    container_name: crud-app
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}
      - MONGODB_URI=${MONGODB_URI}
